# To read the documentation: rustfmt --help=config > rustfmt.txt
tab_spaces = 2
edition = "2021"
max_width = 100
single_line_if_else_max_width = 80
struct_variant_width = 80
struct_lit_width = 50
fn_call_width = 80
use_field_init_shorthand = true