[compiler_options]
include_paths = []

[inputs]
files = ["beam_types.erl"]
directories = ["test_project/src"]

#files = ["test_preproc.erl"]
#directories = ["test_project/src_small"]

exclude_files = []
exclude_directories = []
