[compiler_options]
# TODO not working? include_paths = ["test_project/src"]    # default []

[inputs]
include_paths = ["test_project/src"]      # default []
files = ["*.erl"]                         # default ["*.erl"]
directories = ["test_project/src"]        # default ["."]
exclude_files = []          # TODO: not implemented; default []
exclude_directories = []    # TODO: not implemented; default []
