[package]
name = "libironclad_error"
version = "2022.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libironclad_util = { path = "../libironclad_util" }

glob = "0.3.0"
toml = "0.5.8"
