[package]
name = "libironclad_ppsyntax"
version = "2022.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libironclad_erlsyntax = { path = "../libironclad_erlsyntax" }
